def on_forever():
    while True:
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        basic.pause(100)
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        basic.pause(100)
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        basic.pause(100)
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(392, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(262, music.beat(BeatFraction.WHOLE))
basic.forever(on_forever)
def on_in_background():
    basic.show_string("HALLELUJAH")
control.in_background(on_in_background)
